meal_hippo_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('webplatform.urls', 'webplatform'), namespace='webplatform')),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path

from . import views

app_namespace = 'users'

urlpatterns = [
    path('signup', views.SignUpView.as_view(), name='signup'),
]

webplatform/urls.py
from django.urls import path, include

from . import views

app_namespace = 'webplatform'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_view'),
    path('support', views.SupportView.as_view(), name='support_view'),
    path('contact', views.ContactView.as_view(), name='contact_view'),
    path('supplier/guide', views.SupplierGuideView.as_view(), name='supplier_guide_view'),
    path('order/items', views.OrderItemsView.as_view(), name='order_items_view'),
    path('order/timing', views.OrderTimingView.as_view(), name='order_timing_view'),
    path('order/delivery', views.OrderDeliveryView.as_view(), name='order_delivery_view'),
    path('order/payment', views.OrderPaymentView.as_view(), name='order_payment_view'),
    path('order/notes', views.OrderNotesView.as_view(), name='order_notes_view'),
    path('order/complete', views.OrderCompleteView.as_view(), name='order_complete_view'),
    path('order/history', views.OrderHistoryView.as_view(), name='order_history_view'),
    path('feedback', views.FeedbackView.as_view(), name='feedback_view'),
    path('feedback/thanks', views.FeedbackCompleteView.as_view(), name='feedback_complete_view'),
    path('supplier/signup', views.SupplierSignUpView.as_view(), name='supplier_sign_up_view'),
    path('add_to_order/<int:pk>', views.add_to_order, name='add_to_order'),
    path('remove_from_order/<int:pk>', views.remove_from_order, name='remove_from_order'),
    path('to_be_delivered_toggle', views.to_be_delivered_toggle, name='to_be_delivered_toggle'),
    path('is_individual_toggle/<int:pk>', views.is_individual_toggle, name='is_individual_toggle'),
    path('subscribe_toggle/<path:path>', views.subscribe_toggle, name='subscribe_toggle'),
    path('create_quick_feedback/<email>/<answer>', views.create_quick_feedback, name='create_quick_feedback'),
    path('list', views.ListView.as_view(), name='list_view'),
]

templates/base.html
{% load static %}

{% load templatetags %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23281604-6"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-23281604-6');
    </script>
    <!-- Charset -->
    <meta charset="utf-8">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/e47c63ce68.js" crossorigin="anonymous"></script>
    <!-- Bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %} - Meal Hippo</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- Crisp Chat -->
    <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="236504b4-421b-42dd-a06a-f2b089be0bed";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>
    <!-- Search list -->
    <script type="text/javascript" src="{% static 'search_list.js' %}"></script>
  </head>
  <body>


    <nav class="navbar navbar-expand-md navbar-light py-3">

      <a class="navbar-brand" href="{% url 'webplatform:home_view' %}">Meal&nbsp;Hippo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarText">

        <ul class="navbar-nav ml-auto">
          <li class="nav-item mr-4">
            <a class="nav-link" href="{% url 'webplatform:order_items_view' %}">Order food</a>
          </li>
          {% comment %}<li class="nav-item mr-4">
            <a class="nav-link" href="{% url 'webplatform:list_view' %}">List<small> (new)</small></a>
          </li>{% endcomment %}
          <li class="nav-item mr-4">
            <a class="nav-link" href="{% url 'webplatform:support_view' %}">How it works</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
          {% else %}
            <li class="nav-item mr-4">
          {% endif %}
            <a class="nav-link" href="{% url 'webplatform:contact_view' %}">Get in touch</a>
          </li>
          {% if not user.is_authenticated %}
            <li class="nav-item mr-4">
              <a class="nav-link" href="{% url 'login' %}">Log in</a>
            </li>
            <li class="nav-item">
              <a class="btn btn-primary" href="{% url 'users:signup' %}?next={% url 'webplatform:order_items_view' %}" role="button">Sign up for free</a>
            </li>
          {% endif %}
        </ul>
      </div>

    </nav>

    {% if user.is_authenticated %}
        <nav class="navbar navbar-expand navbar-light user-nav pt-0">
            <ul class="navbar-nav mx-auto ml-md-auto mr-md-0">

              {% if is_subscribed %}
                <li class="nav-item mr-4">
                  <a class="nav-link" data-toggle="modal" data-target="#subscribe_modal" href="">Subscribed <i class="fas fa-toggle-on"></i></a>
                </li>
              {% else %}
                <span data-toggle="tooltip" data-placement="bottom" title="Set up automatic weekly orders and save money">
                  <li class="nav-item mr-4">
                    <a class="nav-link" data-toggle="modal" data-target="#subscribe_modal" href="">Subscribe <i class="fas fa-toggle-off"></i></a>
                  </li>
                </span>
              {% endif %}

              <div class="modal fade" id="subscribe_modal" tabindex="-1" aria-labelledby="subscribe_modal_label" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="subscribe_modal_label"></h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      {% if is_subscribed %}
                        <h5>Are you sure you want to unsubscribe?</h5>
                      {% else %}
                        <h4>Subscribe to Meal Hippo</h4>
                        <p>Here's what you'll get when you subscribe to Meal Hippo:</p>
                        <ul>
                          <li>5% off each order</li>
                          <li>Set up automatic weekly orders next time you create an order</li>
                          <li>We'll email you before each automated order to allow you to change it if you want</li>
                          <li>Cancel anytime</li>
                        </ul>
                      {% endif %}
                    </div>
                    <div class="modal-footer">
                      {% if is_subscribed %}
                        <a class="btn btn-danger btn-block" href="{% url 'webplatform:subscribe_toggle' request.path %}" role="button">Unsubscribe</a>
                      {% else %}
                        <a class="btn btn-primary btn-block" href="{% url 'webplatform:subscribe_toggle' request.path %}" role="button">Subscribe</a>
                      {% endif %}
                      <button type="button" class="btn btn-light btn-block" data-dismiss="modal">Cancel</button>
                    </div>
                  </div>
                </div>
              </div>

              <li class="nav-item mr-4">
                <a class="nav-link" href="{% url 'webplatform:order_items_view' %}">
                  Order <span class="badge badge-secondary">{{ request.user|cart_item_count }}</span>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
                <div class="dropdown-menu dropdown-menu-right">
                  <span class="dropdown-item-text">{{ request.user.email }}</span>
                  <a class="dropdown-item" href="{% url 'webplatform:order_history_view' %}">Order history</a>
                  <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>
              </li>
            </ul>
        </nav>
    {% endif %}

    {% block content %}
    {% endblock %}

    <footer>
      <div class="container-fluid text-center py-5 mb-5">
        <div class="row mb-5 pb-5">
          <div class="col-sm text-sm-left mb-4">
            <span class="logo">
              <a href="{% url 'webplatform:home_view' %}">Meal&nbsp;Hippo</a>
            </span>
          </div>
          <div class="col-sm text-sm-right">
            <p>hello@mealhippo.com</p>
            <p>780-243-7675</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Location -->
    <div class="fixed-bottom ml-3 mb-4 location">
      <span class="rounded text-white px-3 py-2 location-badge">
        <small><i class="fas fa-map-marker-alt"></i>&nbsp;&nbsp;Edmonton</small>
      </span>
    </div>

    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
</html>