meal_hippo_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('webplatform.urls', 'webplatform'), namespace='webplatform')),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path

from . import views

app_namespace = 'users'

urlpatterns = [
    path('signup', views.SignUpView.as_view(), name='signup'),
]

webplatform/urls.py
from django.urls import path, include

from . import views

app_namespace = 'webplatform'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_view'),
    path('support', views.SupportView.as_view(), name='support_view'),
    path('contact', views.ContactView.as_view(), name='contact_view'),
    path('supplier/guide', views.SupplierGuideView.as_view(), name='supplier_guide_view'),
    path('order/items', views.OrderItemsView.as_view(), name='order_items_view'),
    path('order/timing', views.OrderTimingView.as_view(), name='order_timing_view'),
    path('order/delivery', views.OrderDeliveryView.as_view(), name='order_delivery_view'),
    path('order/payment', views.OrderPaymentView.as_view(), name='order_payment_view'),
    path('order/notes', views.OrderNotesView.as_view(), name='order_notes_view'),
    path('order/complete', views.OrderCompleteView.as_view(), name='order_complete_view'),
    path('order/history', views.OrderHistoryView.as_view(), name='order_history_view'),
    path('feedback', views.FeedbackView.as_view(), name='feedback_view'),
    path('feedback/thanks', views.FeedbackCompleteView.as_view(), name='feedback_complete_view'),
    path('supplier/signup', views.SupplierSignUpView.as_view(), name='supplier_sign_up_view'),
    path('add_to_order/<int:pk>', views.add_to_order, name='add_to_order'),
    path('remove_from_order/<int:pk>', views.remove_from_order, name='remove_from_order'),
    path('to_be_delivered_toggle', views.to_be_delivered_toggle, name='to_be_delivered_toggle'),
    path('is_individual_toggle/<int:pk>', views.is_individual_toggle, name='is_individual_toggle'),
    path('subscribe_toggle/<path:path>', views.subscribe_toggle, name='subscribe_toggle'),
    path('create_quick_feedback/<email>/<answer>', views.create_quick_feedback, name='create_quick_feedback'),
    path('list', views.ListView.as_view(), name='list_view'),
]

webplatform/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.views.generic import TemplateView, ListView
from django.views.generic.base import ContextMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib import messages
from django.conf import settings

import stripe
stripe.api_key = settings.STRIPE_API_SECRET_KEY

from . import models
from . import forms
from . import tasks

class IsSubscribedMixin(ContextMixin):
    def get_context_data(self, **kwargs):
        context = super(IsSubscribedMixin, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            user_subscription_qs = models.UserSubscription.objects.filter(user=self.request.user)
            user_subscription = user_subscription_qs[0]
            context['is_subscribed'] = user_subscription.is_subscribed
        return context

class HasFreeDeliveryMixin(ContextMixin):
    def get_context_data(self, **kwargs):
        context = super(HasFreeDeliveryMixin, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            user_delivery_detail_qs = models.UserDeliveryDetail.objects.filter(user=self.request.user)
            user_delivery_detail = user_delivery_detail_qs[0]
            context['free_delivery'] = user_delivery_detail.free_delivery
        return context

class SupportView(IsSubscribedMixin, TemplateView):
    template_name = 'webplatform/support_view.html'

class ContactView(IsSubscribedMixin, TemplateView):
    template_name = 'webplatform/contact_view.html'

class SupplierGuideView(IsSubscribedMixin, TemplateView):
    template_name = 'webplatform/supplier_guide_view.html'

class HomeView(IsSubscribedMixin, HasFreeDeliveryMixin, TemplateView):
    template_name = 'webplatform/home_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['items'] = models.Item.objects.filter(is_active=True, is_featured=True).order_by('rank')
        return context

class OrderItemsView(IsSubscribedMixin, HasFreeDeliveryMixin, ListView):
    model = models.Item
    template_name = 'webplatform/order_items_view.html'
    context_object_name = 'active_items'

    def get_queryset(self):
        return models.Item.objects.filter(is_active=True).order_by('rank')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            order_qs = models.Order.objects.filter(user=self.request.user, is_completed=False)
            if order_qs.exists():
                order = order_qs[0]
                context['order'] = order
                order_items = order.items.all().order_by('item__rank')
                context['order_items'] = order_items
        return context

@login_required
def add_to_order(request, pk):
    item = get_object_or_404(models.Item, pk=pk)
    order_item, created = models.OrderItem.objects.get_or_create(item=item, user=request.user, is_completed=False)
    order_qs = models.Order.objects.filter(user=request.user, is_completed=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__pk=item.pk).exists():
            order_item.quantity += item.portion_increment
            order_item.save()
            messages.info(request, "Portion added")
        else:
            order.items.add(order_item)
            order_item.quantity += (item.minimum_portions - 1)
            order_item.save()
            messages.info(request, "Dish added")
    else:
        order = models.Order.objects.create(user=request.user, is_completed=False)
        order.items.add(order_item)
        order_item.quantity += (item.minimum_portions - 1)
        order_item.save()
        messages.info(request, "Dish added")

        # tasks.send_mail_with_celery.delay(
        #     subject='New order created on mealhippo.com beta',
        #     message='A new order was created on mealhippo.com beta. The user who did this was '+request.user.email+'. This was done at '+str(timezone.localtime(timezone.now()))+'.',
        #     recipient_list=['hello@mealhippo.com'],
        #     html_message='<h1>New order</h1><p>A new order was created on mealhippo.com beta.</p><p>The user who did this was '+request.user.email+'.</p><p>This was done at '+str(timezone.localtime(timezone.now()))+'.</p>',
        # )

    return redirect("webplatform:order_items_view")

def remove_from_order(request, pk):
    item = get_object_or_404(models.Item, pk=pk)
    order_qs = models.Order.objects.filter(user=request.user, is_completed=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__pk=item.pk).exists():
            order_item_qs = models.OrderItem.objects.filter(item=item, user=request.user, is_completed=False)
            order_item = order_item_qs[0]
            if order_item.quantity > item.minimum_portions:
                order_item.quantity -= item.portion_increment
                order_item.save()
                messages.info(request, "Portion removed")
            else:
                order_item.delete()
        else:
            messages.info(request, "No dish to remove")
    else:
        messages.info(request, "No dish to remove")
    return redirect("webplatform:order_items_view")

def to_be_delivered_toggle(request):
    order_qs = models.Order.objects.filter(user=request.user, is_completed=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.to_be_delivered == True:
            order.to_be_delivered = False
            messages.info(request, "Switched to pick up")
        else:
            order.to_be_delivered = True
            messages.info(request, "Switched to delivery")
        order.save()
    return redirect("webplatform:order_items_view")

def is_individual_toggle(request, pk):
    order_item = get_object_or_404(models.OrderItem, pk=pk)
    if order_item.is_individual == True:
        order_item.is_individual = False
        messages.info(request, "Switched to one container")
    else:
        order_item.is_individual = True
        messages.info(request, "Switched to individual containers")
    order_item.save()
    return redirect("webplatform:order_items_view")

def subscribe_toggle(request, path):
    user = request.user
    user_subscription_qs = models.UserSubscription.objects.filter(user=user)
    user_subscription = user_subscription_qs[0]
    if user_subscription.is_subscribed == False:
        user_subscription.is_subscribed = True
        # tasks.send_mail_with_celery.delay(
        #     subject='User has subscribed on mealhippo.com beta',
        #     message='A user has subscribed on mealhippo.com beta. The user who did this was '+user.email+'. This was done at '+str(timezone.localtime(timezone.now()))+'.',
        #     recipient_list=['hello@mealhippo.com'],
        #     html_message='<h1>User subscribed</h1><p>A user has subscribed on mealhippo.com beta.</p><p>The user who did this was '+request.user.email+'.</p><p>This was done at '+str(timezone.localtime(timezone.now()))+'.</p>',
        # )
    else:
        user_subscription.is_subscribed = False
        # tasks.send_mail_with_celery.delay(
        #     subject='User has unsubscribed on mealhippo.com beta',
        #     message='A user has unsubscribed on mealhippo.com beta. The user who did this was '+user.email+'. This was done at '+str(timezone.localtime(timezone.now()))+'.',
        #     recipient_list=['hello@mealhippo.com'],
        #     html_message='<h1>User unsubscribed</h1><p>A user has unsubscribed on mealhippo.com beta.</p><p>The user who did this was '+request.user.email+'.</p><p>This was done at '+str(timezone.localtime(timezone.now()))+'.</p>',
        # )
    user_subscription.save()
    return redirect(path)

class OrderTimingView(IsSubscribedMixin, LoginRequiredMixin, UpdateView):
    login_url = 'login'

    template_name = 'webplatform/order_timing_view.html'

    def get_form_class(self):
        allowed_users = [
            'vanceweir@hotmail.com',
            'brian.neeland@protonmail.com',
            'mlabine103@gmail.com',
            'mike.neeland@gmail.com',
            'Collinsjayden9@gmail.com',
        ]
        if self.request.user.email in allowed_users:
            return forms.OrderTimingFormLate
        else:
            return forms.OrderTimingForm

    def get_object(self):
        order_qs = models.Order.objects.filter(user=self.request.user, is_completed=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.items.count() > 0:
                return order

    def get_success_url(self):
        order_qs = models.Order.objects.filter(user=self.request.user, is_completed=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.to_be_delivered == True:
                return reverse_lazy('webplatform:order_delivery_view')
            else:
                return reverse_lazy('webplatform:order_payment_view')

class OrderDeliveryView(IsSubscribedMixin, LoginRequiredMixin, UpdateView):
    login_url = 'login'

    template_name = 'webplatform/order_delivery_view.html'
    form_class = forms.OrderDeliveryForm
    success_url = reverse_lazy('webplatform:order_payment_view')

    def get_object(self):
        return get_object_or_404(models.UserDeliveryDetail, user=self.request.user)

class OrderNotesView(IsSubscribedMixin, LoginRequiredMixin, UpdateView):
    login_url = 'login'

    template_name = 'webplatform/order_notes_view.html'
    form_class = forms.OrderNotesForm
    success_url = reverse_lazy('webplatform:order_payment_view')

    def get_object(self):

webplatform/templates/webplatform/contact_view.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}Contact{% endblock %}

{% block content %}

<div class="container mb-5">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">

      <div class="jumbotron bg-white mb-0">
        <h3 class="text-center">Contact</h3>
      </div>

      <div class="card-deck mb-5">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Phone</h5>
            <p class="card-text">780-243-7675</p>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Email</h5>
            <p class="card-text">hello@mealhippo.com</p>
          </div>
        </div>
      </div>

    </div>
    <div class="col-2"></div>
  </div>
</div>

<div class="jumbotron jumbotron-fluid bg-medium mb-0">
  <div class="container text-center">
    <div class="row">
      <div class="col-2"></div>
      <div class="col-8">
      <h3 class="mb-4">Get casserole-size meals from local caterers delivered to you.</h3>
      <p><a class="btn btn-primary" href="{% url 'webplatform:order_items_view' %}">Get started</a></p>
    </div>
    <div class="col-2"></div>
    </div>
  </div>
</div>
{% endblock %}

webplatform/templates/webplatform/feedback_complete_view.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load humanize %}

{% block title %}Order{% endblock %}

{% block content %}

<div class="container-fluid my-5">

  <div class="row">

    <div class="col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-12">
      <h3 class="mb-4">Thanks!</h3>
      <p class="mb-4">We appreciate your feedback. It helps us make Meal Hippo better.</p>
      <a href="{% url 'webplatform:order_items_view' %}" class="btn btn-primary btn-block">Back to dishes</a>
    </div>

  </div>

</div>

{% endblock %}

webplatform/templates/webplatform/feedback_view.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load humanize %}

{% block title %}Order{% endblock %}

{% block content %}

<div class="container-fluid my-5">

  <div class="row">

    <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-12">
      <h3 class="mb-4">Feedback</h3>
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn btn-primary btn-block">
      </form>
    </div>


  </div>

</div>

{% endblock %}

webplatform/templates/webplatform/home_view.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}Home{% endblock %}

{% block content %}


{% comment %}
<div class="container">

  <div class="row mt-4 mb-5">

    <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-12">

      <h4>

        <p>Hi everyone&mdash;</p>

        <p>If you have a busy life, it can be difficult to keep up with cooking at home.</p>

        <p>Sometimes, you don't have the time, effort, or skills to cook great, affordable food, three times a day, every day of the year.</p>

        <p>You end up cooking when you would rather be relaxing. Or carving out big spans of time in your weekend to do meal preparation. Or, you settle for quick sub-par meals that aren't as tasty or healthy as you would hope.</p>

        <p>We built Meal Hippo to solve this problem. We want to make it easy for you to get great food day-to-day. The kind of food that you’d make yourself, if you had the time, effort, and skills to do so, every meal.</p>

        <p>Meal Hippo makes it super easy to get casserole-sized meals from local caterers delivered to you.</p>

        <p>We've partnered with a growing list of local caterers who offer great food that you can use to solve your meal planning and home cooking challenges.</p>

      </h4>

      <div class="text-center">
        <div class="mt-5">
          <a href="{% url 'webplatform:order_items_view' %}" class="btn btn-attention btn-lg btn-order" role="button">Order food</a>
          {% if user.is_authenticated and free_delivery or not user.is_authenticated %}<br><small>Free delivery with first order</small>{% endif %}
        </div>
        <div class="mt-3 mb-4">
          <a href="{% url 'webplatform:support_view' %}" class="btn btn-light" role="button">Learn more</a>
        </div>
      </div>

    </div>

  </div>

</div>

<div class="container">
  <hr>
</div>
{% endcomment %}



<!-- <div class="jumbotron jumbotron-fluid bg-white text-center text-sm-left pb-0"> -->
<div class="jumbotron jumbotron-fluid bg-white text-center pb-0">
  <div class="container">
    <div class="row">
      <!-- <div class="col-md-9"> -->
      <div class="col-lg-10 offset-lg-1">
        <!-- <h1 class="mb-4">Order home-style food from chefs and caterers in your area</h1> -->
        <h1 class="title mb-4">Lunches and suppers, without cooking</h1>
        <h4 class="mb-4 px-lg-5 mx-lg-5">
          Meal Hippo solves your meal planning and home cooking challenges by making it easy to get casserole-sized meals from local caterers delivered to you.
        </h4>
        <h5>
          <span class="badge badge-pill badge-info p-2 px-3 mb-3"><i class="fas fa-check"></i>&nbsp;&nbsp;Bulk portions for multiple meals</span>&nbsp;
          <span class="badge badge-pill badge-info p-2 px-3 mb-3"><i class="fas fa-check"></i>&nbsp;&nbsp;No prep, no cooking</span>&nbsp;
          <span class="badge badge-pill badge-info p-2 px-3 mb-3"><i class="fas fa-check"></i>&nbsp;&nbsp;Ready to eat</span>
        </h5>
        <!-- <p>
          Great home-style food you want to eat everyday<br>
          Fully cooked, prepared, and ready to eat&mdash;no prep, no cooking<br>
          Made to order with fresh ingredients by local, independent chefs and caterers<br>
          Subscribe to automate weekly orders
        </p> -->

        <div class="mt-4">
          <a href="{% url 'webplatform:order_items_view' %}" class="btn btn-attention btn-lg btn-order" role="button">Order food</a>
          {% if user.is_authenticated and free_delivery or not user.is_authenticated %}<br><small>Free delivery with first order</small>{% endif %}
        </div>
        <div class="mt-3 mb-4">
          <a href="{% url 'webplatform:support_view' %}" class="btn btn-light" role="button">Learn more</a>
        </div>

      </div>
    </div>
  </div>
</div>



<div class="container my-5">
  <div class="card-group shadow">
    {% for item in items %}
      <div class="card border-top-0 border-bottom-0 border-left-0">
        <a href="{% url 'webplatform:order_items_view' %}" class="featured">
          <img src="{% static 'webplatform/'|add:item.name|add:'.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text text-center">{{ item.name }}
            </p>
          </div>
          {% comment %}<div class="card-footer bg-white text-center">
            <small>{{ item.supplier.business_name }}</small>
          </div>{% endcomment %}
        </a>
      </div>
    {% endfor %}
      <div class="my-auto mx-auto text-center"><a href="{% url 'webplatform:order_items_view' %}" class="py-2 px-4" data-toggle="tooltip" data-placement="bottom" title="See all dishes"><i class="fas fa-angle-right"></i></a></div>
  </div>
  <div class="my-5 text-center">
    <a href="{% url 'webplatform:order_items_view' %}" class="btn btn-primary" role="button">See all dishes</a>
  </div>
</div>


<div class="jumbotron jumbotron-fluid bg-light mb-0">

  <div class="container">

    <h3 class="text-center mb-5">How can I use Meal Hippo?</h3>
    <h5 class="text-center mb-3">Meal Hippo offers casserole-size dishes that replace regular cooking at home.</h5>
    <h5 class="text-center mb-5">Save time and effort. Order here and cook less.</h5>

    <div class="card-deck">
      <div class="card shadow border-0">
        <div class="card-body">
          <h5 class="card-title">Meal prep lunches&nbsp;&nbsp;<span class="text-grey"><i class="fas fa-box"></i></span></h5>
          <p class="card-text">Get one large multi-portion dish at the beginning of the week and use it for packed lunches.</p>
        </div>
      </div>
      <div class="card shadow border-0">
        <div class="card-body">
          <h5 class="card-title">Family dinners&nbsp;&nbsp;<span class="text-grey"><i class="fas fa-utensils"></i></span></h5>
          <p class="card-text">Take a few nights off from cooking dinner by getting ready-to-eat dishes delivered to your house.</p>
        </div>
      </div>
      <div class="card shadow border-0">
        <div class="card-body">
          <h5 class="card-title">Take a break on busy weeks&nbsp;&nbsp;<span class="text-grey"><i class="fas fa-couch"></i></span></h5>
          <p class="card-text">Get a few casserole-size meals delivered when you're busy. Plan ahead for busy weeks by ordering a few dishes ahead of time.</p>
        </div>
      </div>
    </div>

    <div class="text-center mt-5">
      <p><a class="btn btn-primary" href="{% url 'webplatform:order_items_view' %}" role="button">Get started</a></p>
    </div>

  </div>

</div>


<div class="jumbotron jumbotron-fluid bg-white mb-0">

  <div class="container">

    <h3 class="text-center mb-5">How does Meal Hippo work?</h3>
    <h5 class="text-center mb-5">Ordering with Meal Hippo is simple.</h5>

    <div class="card-deck mx-5">
      <div class="card shadow border-0">
        <div class="card-body">
          <h5 class="card-title">Order online&nbsp;&nbsp;<span class="text-grey"><i class="fas fa-laptop"></i> <small><i class="fas fa-mobile-alt"></i></small></span></h5>
          <p class="card-text">Choose from several dishes offered by caterers in your area.</p>
          <p class="card-text">Choose your delivery date and time.</p>
          <p class="card-text">Pay online.</p>
        </div>
      </div>
      <div class="card shadow border-0">
        <div class="card-body">
          <h5 class="card-title">Delivery&nbsp;&nbsp;<span class="text-grey"><i class="fas fa-shipping-fast"></i></span></h5>
          <p class="card-text">Your order is delivered to you, fresh.</p>
          <p class="card-text">We make sure you receive you order safely.</p>
        </div>
      </div>
    </div>

    <div class="text-center mt-5">
      <p><a class="btn btn-primary" href="{% url 'webplatform:order_items_view' %}" role="button">Get started</a></p>
    </div>

  </div>

</div>



{% comment %}
<div class="jumbotron jumbotron-fluid bg-light mb-0 text-right">
  <div class="container p-5">
    <h4>Real food you want to eat everyday</h4>
    <p>The food on Meal Hippo is made by caterers and chefs, who make the kind of food your mom would make&mdash;not restaurant food.</p>
  </div>
</div>

<div class="jumbotron jumbotron-fluid bg-white mb-0 text-left">
  <div class="container p-5">
    <h4>Fully coooked and prepared&mdash;no prep, no cooking</h4>
    <p>The food on Meal Hippo is already fully cooked. No need to finish the cooking yourself.</p>
  </div>
</div>

<div class="jumbotron jumbotron-fluid bg-light mb-0 text-right">
  <div class="container p-5">
    <h4>Subscribe for convenience</h4>
    <p>As an option, get your food order delivered weekly so you don't have to plan meals repeatedly.</p>
  </div>
</div>

<div class="jumbotron jumbotron-fluid bg-medium mb-0 text-center">
  <div class="container p-5 mb-5">
    <h3>How you can use Meal Hippo</h3>
    <div class="card-group shadow">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Meal prep lunches 📦</h5>
          <p class="card-text">Get one large multi-portion dish at the beginning of the week and use it for packed lunches.</p>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Family dinners 🍽️</h5>
          <p class="card-text">Take a few nights off from cooking dinner by getting ready-to-eat dishes delivered to your house.</p>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Take a break on busy weeks 🛋️</h5>
          <p class="card-text">Get a few meals delivered when you're busy. Plan ahead for busy weeks by ordering a few dishes ahead of time.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="text-center mb-3">
    <a class="btn btn-primary" href="{% url 'webplatform:order_items_view' %}" role="button">Get started</a>
  </div>
</div>
{% endcomment %}

{% endblock %}

webplatform/templates/webplatform/order_complete_view.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load humanize %}

{% block title %}Order{% endblock %}

{% block content %}

<div class="container-fluid my-5">

  <div class="row">




    <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-12">

      <p><b>Order completed</b></p>
      <h3 class="mb-4">Thank you for using Meal&nbsp;Hippo!</h3>

      <p>Your order will be delivered in the date and time window that you specified.</p>
      <p>We've just sent you an email confirming your order.</p>
      <p>Access your order history:<br>
        <a href="{% url 'webplatform:order_history_view' %}">mealhippo.com/order/history</a>
      </p>

      <div class="card mt-4">
        <div class="card-body">
          <p>If you have a moment, we would love to get your feedback on Meal Hippo. This helps us make Meal Hippo better.</p>
          <a href="{% url 'webplatform:feedback_view' %}" class="btn btn-primary btn-block">Give feedback</a>
        </div>
      </div>




    </div>



  </div>

</div>

{% endblock %}

webplatform/templates/webplatform/order_delivery_view.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load humanize %}

{% block title %}Order{% endblock %}

{% block content %}

<div class="container-fluid my-5">

  <div class="row">

    <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-12">
      <p>Step <b>2 of 3</b> <small>&hellip; stay with us &hellip;</small></p>
      <h3 class="mb-4">Enter or edit your delivery details</h3>
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Continue" class="btn btn-primary btn-block">
      </form>
    </div>


  </div>

</div>

{% endblock %}

webplatform/templates/webplatform/order_notes_view.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load humanize %}

{% block title %}Order{% endblock %}

{% block content %}

<div class="container-fluid my-5">

  <div class="row">

    <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-12">
      <h3 class="mb-4">Anything you'd like us to know about this order?</h3>
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Continue" class="btn btn-primary btn-block">
        <a href="{% url 'webplatform:order_payment_view' %}" class="btn btn-light btn-block" role="button">Cancel</a>
      </form>
    </div>


  </div>

</div>

{% endblock %}

webplatform/templates/webplatform/order_timing_view.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load humanize %}

{% block title %}Order{% endblock %}

{% block content %}

<div class="container-fluid my-5">

  <div class="row">

    <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-12">
      {% if order.to_be_delivered %}
        <p>Step <b>1 of 3</b></p>
      {% else %}
        <p>Step <b>1 of 2</b></p>
      {% endif %}
      {% if order.to_be_delivered %}
        <h3 class="mb-4">When do you want your order delivered?</h3>
      {% else %}
        <h3 class="mb-4">When do you want to pick up your order?</h3>
      {% endif %}
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Continue" class="btn btn-primary btn-block">
      </form>
    </div>

  </div> <!-- row -->

</div> <!-- container -->

{% endblock %}

webplatform/templates/webplatform/supplier_sign_up_view.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load humanize %}

{% block title %}Order{% endblock %}

{% block content %}

<div class="container-fluid my-5">

  <div class="row">

    <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-12">
      <p>CATERER</p>
      <h3 class="mb-4">Sign-Up Form</h3>
      <p>Please enter your information to start a caterer account with Meal Hippo.</p>
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn btn-primary btn-block">
      </form>
    </div>


  </div>

</div>

{% endblock %}